### PR TITLE
Support the addition of new body parts after having started labeling

### LINKED ISSUE #2125: Cant add a new body part after training
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Bug description

After labeling and training I decided to add another body part label to my analysis. 

According to the Neth et al. 2019 paper - 
"Occasionally, the user might want to label additional body parts. In such a case, the user needs to append the new labels to the bodyparts list in the config.yaml file. Thereafter, the user can call the function label_frames and will be asked if he or she wants to display only the new labels or all labels before loading the frames. Saving the labels after all the images are labeled will append the new labels to the existing labeled dataset."

I added the newly desired body part to the config.yaml file. However, when pressing 'Label frames' in the Label frames tab napari opens but  I am never asked if I want to display only the new or all the labels. The new body part does not appear in the key point selection list. 

Maybe I am missing something in the process? any other way to add a new body part label to my videos?  

### Operating System

Windows

### DeepLabCut version

DLC 2.3

### DeepLabCut mode

single animal

### Device type

GPU

### Steps To Reproduce

_No response_

### Relevant log output

_No response_

### Anything else?

Really enjoying working with DLC! Thank you so much for the support! 

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/DeepLabCut/DeepLabCut/blob/master/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by jeylau**
Fixes https://github.com/DeepLabCut/DeepLabCut/issues/2125

### CODE REVIEW

**Comment by jeylau** [comment]
Can this one be merged @MMathisLab? ☺️

**Review by MMathisLab — APPROVED** [review]

**Comment by MMathisLab** [comment]
Hey @jeylau @ yes, sorry-- could u fix merge conflict, then good to go!

**Comment by jeylau** [comment]
No worries! It's done!

**Comment by MMathisLab** [comment]
seems test failing, otherwise fine to merge

**Comment by jeylau** [comment]
I'll merge @MMathisLab; it seems to be a temporary GitHub CI issue like we and others experienced in the past (e.g., https://github.com/actions/runner-images/issues/6913), and all unit tests pass locally.

**Pull request merged**
