### PR TITLE
Minor Refactor: Replace path normalization function with standard library function

### PR DESCRIPTION
**Pull request by nickdelgrosso**
Hi,

This project looks very useful, and I'd love to use it for my group.  I understand it's a new project, so no worries; while doing some code review, I came across this quick improvement: replacing the `to_os_dir_sep()` function with the `os.path.normpath()` function.  They have the same interface, and the nice thing is that the `normpath()` function doesn't raise an error if it encounters a mix of path seperators.

Best wishes,

Nick

### CODE REVIEW

**Comment by jeylau** [comment]
Hello @nickdelgrosso, thanks for the input! `os.path.normpath` does not do what I'm after; e.g., on my Mac:
```python
path = 'C:\\Users\\me\\Desktop'
print(os.path.normpath(path))
>>> 'C:\\Users\\me\\Desktop'
```
whereas I really want what `to_os_dir_sep` returns:
```python
print(to_os_dir_sep(path))
>>> 'C:/Users/me/Desktop'
```
That is, a conversion of path separators to the current OS regardless of whether the path is Unix or Posix.

**Comment by nickdelgrosso** [comment]
Hi @jeylau,

Thanks for the code review, apologies for the bad code.  I didn't realize it, but it looks like `os.path.normpath` doesn't do much on Linux and Mac systems.  I've just updated it with a version that corrects mixed path separators without raising an error, this time actually testing it out on both Windows and Linux.  Can you take a look again?

Best wishes,

Nick

**Comment by jeylau** [comment]
Thanks for the update! Why did you add `self` to the function signature and get rid of the docstrings?
Doing it your way breaks the function, since '\\' can be valid in some Unix paths as noted by the user who originally wrote the function.
You should not have paths with mixed separators when using DeepLabCut though: perhaps this is something I can help you with? There may be a bug I should catch. 🤔

**Comment by nickdelgrosso** [comment]
Oh my goodness, I have no idea why I did that; I guess I'm more tired than I thought. One more reason to include tests with submission, even for simple functions.  There's really no reason on my side I needed the the function, I just saw it and thought there might be a simpler way to handle paths; I'm very sorry to have wasted your time. Feel free to just close the pull request, it's clearly not helping anyone 😅

**Pull request closed without merging**
