### PR TITLE
Bypass the "choose reader" dialog window

### LINKED ISSUE #3: Get rid of the « choose reader » dialog when dropping folders

### PR DESCRIPTION
**Pull request by jeylau**
Fixes #3

### CODE REVIEW

**Comment by MMathisLab** [comment]
seems related :) https://github.com/napari/napari/issues/4613

**Comment by MMathisLab** [comment]
at least for me, this box still pops up,  but maybe I am not understanding the PR 
Screen Shot 2022-06-03 at 2 08 09 PM

**Comment by jeylau** [comment]
Mhhhh this is strange, it does silence it in my case. Let me look at it more closely.

**Comment by jeylau** [comment]
I cannot reproduce it @MMathisLab; it works fine on my machine with both pyside2 and pyqt5 🤔

**Comment by MMathisLab** [comment]
so strange,
Screen Shot 2022-06-03 at 5 28 09 PM


just to be sure; I `git checkout choose_reader`
run `pip install -e. `
then launch `napari  `
plugins > napari-deeplabcut

**drag and drop** labeled-data subfolder (also tried open > folder) into workspace:

Screen Shot 2022-06-03 at 5 31 38 PM

**Comment by jeylau** [comment]
And you activate the napari-deeplabcut plugin from the Plugins menu, right? 🤔

**Comment by MMathisLab** [comment]
yeah exactly, go to bar, plugins > dlc ...  strange! But, otherwise looks good if it work for you, the other branches I could test and working great! :)

**Pull request merged**
